---
deployment:
  tasks:
    - cp -a /home/desa7677/laravel-app/public/. /home/desa7677/public_html/
    - cp -a /home/desa7677/laravel-app/public/.htaccess /home/desa7677/public_html/ 2>/dev/null || true

    - /usr/bin/rsync -a --delete --exclude='.env' --exclude='storage/logs' --exclude='storage/app' /home/desa7677/repositories/laravel-app/ /home/desa7677/laravel-app/
    - cd /home/desa7677/laravel-app && /usr/local/bin/php artisan config:cache
    - cd /home/desa7677/laravel-app && /usr/local/bin/php artisan route:cache
    - cd /home/desa7677/laravel-app && /usr/local/bin/php artisan view:cache
    - cd /home/desa7677/laravel-app && /usr/local/bin/php artisan migrate --force
